version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.12'

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py
  builder: dirhtml

# Optionally build your docs in additional formats such as PDF and ePub
formats: []

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements-dev.lock
