name: 'Release new version'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        run: |
          pip install hatch
          hatch build
          ls -l dist
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
  gh-release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          bodyFile: '.github/release-body.md'
          draft: false
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          prerelease: false
  publish-pypi:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && ${{ needs.prepare.outputs.is-release }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

